#!/usr/bin/env bash

REPOSITORY="https://github.com/moep/shellscripts"
LIB_DIR="${HOME}/.local/lib/shellscripts"
SRC_DIR=$(dirname "${BASH_SOURCE[0]}")
FISH_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/fish

# 1 = false; 0 = true
opt_dl=false
opt_force=false
opt_uninstall=false

__last_file=""

function is_from_source() {
  local remote=$(cd "${SRC_DIR}" && git remote -v 2> /dev/null | head -1 | cut -f 2 | cut -d ' ' -f 1)
  if [[ "${remote}" == "${REPOSITORY}" ]]; then
    return 0
  else 
    return 1
  fi
}

function clone() {
  local tmp_dir=$(mktemp -d)
  rc=$?
  
  if [[ $rc -ne 0 ]]; then
    echo "Could not create tmp dir."
    exit 1
  fi

  echo " [*] Cloning into ${tmp_dir}..."
  git clone "${REPOSITORY}" "${tmp_dir}"

  SRC_DIR=$tmp_dir
}

function promptyn() {
  local question=$1
  local input

  echo -n "${question} [y|n]: "
  while true; do
    read -n 1 -s input

    case "$input" in
      'y'|'Y')
        echo "${input}"
        return $(true)
      ;;
      'n'|'N')
        echo "${input}"
        return $(false)
      ;;
    esac

  done
}

function has_fish() {
  command -v fish > /dev/null
}


function has_bash() {
  command -v bash > /dev/null
}

function append_line() {
  local file="$1"
  local line="$2"
  local pattern="${3:-$line}"

  local line_no=""

  if [[ "${file}" != "${__last_file}" ]]; then
    __last_file="${file}"
    echo
    echo " == ${file} =="
  fi

  if [[ ! -f "${file}" ]]; then
    echo "ERROR: File not found."
    return 1
  fi

  line_no=$(grep -nF "${pattern}" "${file}" | sed 's/:.*//' | tr '\n' ' ')

  if [[ -n "${line_no}" ]]; then
    echo " ~ ${line}"
  else
    echo " + ${line}"
    echo "${line}" >> "${file}"
  fi

}

function remove_line() {
  local file="$1"
  local pattern="$2"

  local line_nums=()
  local line=""
  local sed_nums=""
  local file_src=$(readlink "${file}")

  file=${file_src:-"$file"}

  if [[ "${file}" != "${__last_file}" ]]; then
    __last_file="${file}"
    echo
    echo " == ${file} =="
  fi

  line_nums=($(grep -nE "${pattern}" "${file}" | sed 's/:.*//' | tr '\n' ' ' | sort))

  for line_no in $line_nums; do
    echo " - $(sed -n "${line_no}p" "${file}")"
    sed_nums+="${line_no}d;"
  done

  sed -i.bak -e "${sed_nums}" "${file}"
}

function install() {
  # shellscript lib
  echo " [*] Copying sources from ${SRC_DIR} to ${LIB_DIR}"
  cp "${SRC_DIR}/bootstrap.sh" "${LIB_DIR}/"
  cp -r "${SRC_DIR}/contrib" "${LIB_DIR}/"
  cp -r "${SRC_DIR}/lib" "${LIB_DIR}/"
  cp -r "${SRC_DIR}/shellscriptloader-0.2" "${LIB_DIR}/"
  
  # add library entry to fish config
  if has_fish; then
    if promptyn "Do you want to add the library path variable to your config.fish?"; then
      append_line "${FISH_DIR}/config.fish" \
        "# Autmatically added by shell script lib installer"

      append_line "${FISH_DIR}/config.fish" \
        "set -gx BASH_SCRIPT_PATH ${LIB_DIR}" \
        "set -gx BASH_SCRIPT_PATH" 
    fi
  fi

  # add library to bash config
  if has_bash; then
    if promptyn "Do you want to add the library path variable to your .bashrc?"; then
      append_line "${HOME}/.bashrc" \
        "# Autmatically added by shell script lib installer"

      append_line "${HOME}/.bashrc" "BASH_SCRIPT_PATH=${LIB_DIR}" 
    fi
  fi
}

function uninstall() {
  promptyn "Do you really want to remove the shell script library?" || exit 1

  echo " [*] Removing ${LIB_DIR}"
  rm -rf "${LIB_DIR}"

  if has_fish; then
    echo " [*] Removing entries from ${FISH_DIR}/config.fish"

    remove_line "${FISH_DIR}/config.fish" \
        "# Autmatically added by shell script lib installer"

    remove_line "${FISH_DIR}/config.fish" "^set -gx BASH_SCRIPT_PATH"
  fi

  if has_bash; then
    echo " [*] Removing entries from ${HOME}/.bashrc"

    remove_line "${HOME}/.bashrc" \
      "# Autmatically added by shell script lib installer"

    remove_line "${HOME}/.bashrc" "BASH_SCRIPT_PATH=${LIB_DIR}" 
  fi

  exit 0
}

function print_help() {
  echo "$(basename $0) (OPTS)"
  cat <<EOF
OPTS:
  --download       Force download even if called from git sources.
  --force          Force reinstallation.
  --uninstall      Uninstall and exit.
  -h, --help, -?   Print this message.
EOF
}

function parse_args() {
  for arg in "$@"; do
    case $arg in
      --download)
        opt_dl=true
        shift
      ;;
      --force)
        opt_force=true
        shift
      ;;
      --help|-h|-?)
        print_help
        exit 0
      ;;
      --uninstall)
        uninstall
      ;;
      *)
        print_help
        exit 1
      ;;
    esac
  done
}

function main() {
  parse_args "$@"

  #has_fish_config && echo "has fish config"
  #is_from_source && echo "is from source"
  #$opt_dl && echo "opt_dl"
  #$opt_force && echo "opt_force"

  if [[ -d "${LIB_DIR}" ]]; then
    echo "DEBUG: " $(pwd $LIB_DIR)
    echo "It looks like the library is already installed at ${LIB_DIR}."
    promptyn "Do you want to proceed?" || exit 0
  else
    echo " [*] mkdir ${LIB_DIR}"
    mkdir -p "${LIB_DIR}" 
  fi 

  # Script was called via curl -> download sources
  if ! is_from_source || $opt_dl; then
    clone
  fi

  install
}

main "$@"



# DEBUG

#parse_args "$@"
#has_fish_config && echo "has fish config"
#is_from_source && echo "is from source"
#$opt_dl && echo "opt_dl"
#$opt_force && echo "opt_force"
